# Meta data
name:         GoodToRead Downloader
authors:      Fernando Paladini
description:  Download all your desired books directly from GoodReads or Facebook list.

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       docs
port:         4000
url:          http://photonkit.com
